### ISSUE TITLE
Dealing with a game which offsets crosshair

### ISSUE THREAD

**Issue by nrliii** [Exunys/AirHub#2]
![image](https://user-images.githubusercontent.com/69441714/232072542-789a1721-5904-4a89-9072-8c929b2366ae.png)

How would i deal with such games

**Comment by Exunys** [comment]
Which crosshair is the one from airhub, the green one or the white one? And also if possible please link me the game thanks!

**Comment by nrliii** [comment]
Its the green one and here is the game https://www.roblox.com/games/12441918692/BETA-Area-51

**Comment by Exunys** [comment]
Hello, the positioning is just fine, however I am aware that this is an occurring problem for krnl users. You can report this bug to the developers of your exploit, there is nothing I can do here sadly because It is not an issue on my end. Thank you for the understanding.

https://user-images.githubusercontent.com/76539058/232212639-ec780f59-ce90-4af8-a5ce-22ce2f373df4.mp4

**Comment by nrliii** [comment]
Huh strange since im using synapse? And it only happens when you are holding a gun

**Comment by Exunys** [comment]
I wasn't able to get a gun I had no clue how the game worked, if you care to explain dm me on discord.
